FROM --platform=linux/amd64 rust:1.81.0-bullseye


RUN apt update -y && \
    apt upgrade -y && \
    apt install -y git curl iputils-ping dnsutils && \
    apt autoremove -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Change the target path for Rust
RUN mkdir -p /.rust/target
ENV CARGO_TARGET_DIR=/.rust/target

WORKDIR /app
